---
title: "Homework 1"

output:
  rmarkdown::github_document:
    toc: true

# output:
#   html_document:
#     toc: yes
    
# output:
#   html_notebook:
#     toc: yes

# output: word_document
---
```{r dependencies, message=FALSE, warning=FALSE, paged.print=FALSE}
# load dependencies
library(tidyverse)
library(pander)

```
#Data
##Read
```{r read data}
df <- as_tibble(read.csv("~/Development-Economics/data/index_test_data.csv"))

```

##Inspect
```{r}
df %>%
  pander()

```

##Normalize
"Normalization Process: Divide (cardinal number – minimum) by (maximum – minimum)"
```{r}
normalize<-function(x){
   (x - min(x)) / (max(x) - min(x))
 }

norm.df <- df %>%
  mutate_if(is.numeric, funs(normalize))

norm.df %>%
  pander()

```

##Weighting
###Assign Weights
```{r}
# weights
pollution.index.wt <- 0.25
cost.of.living.wt <- 0.2
language.wt <- 0.15
misc.amen.wt <- 0.4

weights <- c(pollution.index.wt,
             cost.of.living.wt,
             language.wt,
             misc.amen.wt)

# confirm weights sum to 1
sum(weights) == 1

```

###Weight Data
```{r}
weighted.norm.df <- norm.df %>%
  mutate(Pollution.index = Pollution.index * pollution.index.wt) %>%
  mutate(Cost.of.living = Cost.of.living * cost.of.living.wt) %>%
  mutate(Language = Language * language.wt) %>%
  mutate(Misc.Amenities = Misc.Amenities * misc.amen.wt)

weighted.norm.df %>%
  pander()

```


```{r}
weighted.norm.df %>%
  filter(City %in% "Shanghai") %>%
  pander()

```


```{r}
emphasize.strong.rows(which(weighted.norm.df$City == "Shanghai", arr.ind = TRUE))

pander(weighted.norm.df)

```








