---
title: "HW1"
author: "Team Syria"

# output:
#   html_notebook:
#     toc: yes
#     toc_float: yes

# output:
#   html_document:
#     toc: yes
#     toc_float: true
    
output:
  rmarkdown::github_document:
    toc: true
---

<style>
    body .main-container {
        max-width: 90%;
    }
</style>


```{r}
library(googledrive)
library(tidyverse)
library(readxl)
library(lubridate)
library(pander)
# library(ggmap)
library(scales)

```

```{r}
combo <- read_excel("~/Development-Economics/data/combo.xlsx")

```

```{r}
normalize <- function(x){
  round((x - min(x)) / (max(x) - min(x)), digits = 2)
}

```

```{r}
# weight_negatively <- function(x){
  # x <- x * -1
# }

```


```{r}
combo_norm <- combo %>%
  mutate_if(is.numeric, funs(normalize))

```

```{r}
Score <- combo_norm %>%
  group_by(Country) %>%
  summarise(sum = sum(`Improved water source (% of population with access)`,
                      `Life expectancy at birth, total (years)`,
                      `Urban population growth (annual %)`,
                      `Adult Literacy Rate (% Ages 15 and older)`,
                      `Population with at least some secondary education (% ages 25 and older)`,
                      `Mean years of schooling (years)`,
                      `Inequality in education (%)`,
                      `GNI per capita (2011 PPP$)`,
                      `Press Freedom Score (0 worst - 100 best)`)) %>%
  as.matrix() %>%
  t()

Score <- Score[-1,]

```

```{r}
pander::panderOptions('table.split.table', Inf)

emphasize.strong.cols(which(combo_norm$Country == "Syria",
                            arr.ind = TRUE))

combo_norm_matr_trans <- combo_norm %>%
  as.matrix() %>%
  t() %>%
  na.omit() 

combo_matrix <- rbind(combo_norm_matr_trans, Score)

# emphasize.strong.rows(1)
emphasize.strong.rows(c(1, nrow(combo_matrix)))

```

```{r}
pander(combo_matrix)

```

```{r}
map_world <- map_data(map = "world")

# Score <- combo_norm %>%
#   group_by(Country) %>%
#   summarise(sum = sum(`Improved water source (% of population with access)`,
#                       `Life expectancy at birth, total (years)`,
#                       `Urban population growth (annual %)`,
#                       `Adult Literacy Rate (% Ages 15 and older)`,
#                       `Population with at least some secondary education (% ages 25 and older)`,
#                       `Mean years of schooling (years)`,
#                       `Inequality in education (%)`,
#                       `GNI per capita (2011 PPP$)`,
#                       `Press Freedom Score (0 worst - 100 best)`))

index_countries <- combo_norm %>%
  group_by(Country) %>%
  summarise(`Index Sum` = sum(`Improved water source (% of population with access)`,
                    `Life expectancy at birth, total (years)`,
                    `Urban population growth (annual %)`,
                    `Adult Literacy Rate (% Ages 15 and older)`,
                    `Population with at least some secondary education (% ages 25 and older)`,
                    `Mean years of schooling (years)`,
                    `Inequality in education (%)`,
                    `GNI per capita (2011 PPP$)`,
                    `Press Freedom Score (0 worst - 100 best)`)) %>%
  inner_join(map_world, by = c("Country" = "region")) 

nonindex_countries <- map_world %>%
  anti_join(combo_norm, by = c("region" = "Country"))


index_map <- NULL

```

```{r}
index_map <- ggplot() +
  geom_polygon(data = index_countries,
               aes(x = long, y = lat,
                   group = group,
                   # fill = total_map$`Press Freedom Score (0 worst - 100 best)`),
                   fill = `Index Sum`),  size = 0.01) +
  geom_polygon(data = nonindex_countries,
               aes(x = long, y = lat, group = group),
               # alpha = 0.1,
               fill = "white",
               size = 0.1) +
  coord_map() +
  scale_fill_distiller(type = "seq",
                       palette = "RdBu",
                       breaks = pretty_breaks(n=10), 
                       direction = 1) +
  coord_fixed(ratio = 1.5) +
  guides(fill = guide_legend(keywidth = 1, keyheight = 3, reverse = TRUE))

```

```{r fig.height=8, fig.width=12}
index_map

```

